
durable-consumer:
  queue: q-perf-test
  directExchange: x-incoming-transaction
  routingKey: q-perf-test


spring:
  security:
    oauth2:
      client:
        provider:
          uaa:
            tokenUri: http://localhost:8080/uaa/oauth/token

        registration:
          consumer:
            clientId: consumer
            clientSecret: consumer
            provider: uaa
