server:
  port: 8081

security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        key-value: tokenKey
    client:
      clientId: consumer
      clientSecret: consumer_secret
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
